apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmaster-deployment
  labels:
    app: taskmaster-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmaster-app
  template:
    metadata:
      labels:
        app: taskmaster-app
    spec:
      containers:
        - name: taskmaster-app
          image: dineshbagne/taskmaster-python:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always